---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# moveworkflow

<!-- badges: start -->
<!-- badges: end -->

The goal of moveworkflow is to ...

## Installation

You can install the development version of moveworkflow from [GitHub](https://github.com/) with:


```{r eval= FALSE}
## Set timezone system
Sys.setenv(TZ = "UTC") #set in UTC to avoid any problem, but timezone projet = UTC+1
```

``` {r eval= FALSE}
## Combined diver
feature_file <- type_files("CSV") #set file characteristic
save_directory <-system.file("data_ext","data_compile","diver",package="moveworkflow", mustWork=TRUE) #set save directory
name_diver <- c("A_1_diver","A_2_diver","A_3_diver","Baro_amboise","N_F_diver","N_A_diver","Baro_noizay") #list diver to combine
for (i in name_diver){
  directory <- system.file("data_ext","data_raw",i,package="moveworkflow", mustWork=TRUE)
  data_combine <- combine_files(directory, "CSV") %>% 
    dplyr::select(1:4) %>% 
    dplyr::rename_with(~feature_file$col_name, everything()) %>%
    dplyr::distinct(date_time, .keep_all = TRUE) %>% 
    dplyr::arrange(date_time) %>% 
    filter(date_time < "2025-04-11 00:00:00")
  name_file <- paste(basename(directory),"_combine.csv",sep="")
  save_file(save_directory,data_combine,"date_time",name_file) #save with name = name_file
}


##Compiled all combine_diver
directory <- system.file("data_ext","data_compile","diver",package="moveworkflow", mustWork=TRUE) #set folder directory to compiled
feature_file <- type_files("csv") #set file characteristic
col_name <- c("date_time", "level_cm", "id_sensor", "id_plot") #set column names
data_combine <- combine_files(directory, "csv") %>% 
  dplyr::select(-temp_c) %>% 
  dplyr::rename_with(~col_name, everything()) %>% 
  dplyr::arrange(date_time)
save_directory <-system.file("data_ext","data_compile",package="moveworkflow", mustWork=TRUE)
name_file <- paste(basename(directory),"_combine.csv",sep="")
save_file(save_directory,data_combine,"date_time",name_file) #save with name = name_file
rm(list = ls())
```

``` {r eval= FALSE}
## Combined tipping
feature_file <- type_files("txt") #set files characteristics
save_directory <-system.file("data_ext","data_compile","tipping",package="moveworkflow", mustWork=TRUE) #set save directory
name_tipping <- c("A_1_tipping","A_2_tipping","A_3_tipping","N_F_tipping","N_A_tipping") #set names tipping to combine

for (i in name_tipping){
  directory <- system.file("data_ext","data_raw",i,package="moveworkflow", mustWork=TRUE) 
  data_combine <- combine_files(directory, "txt") %>% 
    dplyr::select(1:3,id_file) %>% 
  dplyr::rename_with(~feature_file$col_name, everything()) %>%
  dplyr::select(-row_name) %>% 
  dplyr::mutate(value = as.numeric(gsub(",","",value))) %>% #delete "," as thousand separator
  base::subset(!is.na(value)) %>% 
  dplyr::arrange(date_time)
  name_file <- paste(basename(directory),"_combine.csv",sep="")
  save_file(save_directory,data_combine,"date_time",name_file) #save with name = name_file
}

##Compiled all tipping_combine
directory <- system.file("data_ext","data_compile","tipping",package="moveworkflow", mustWork=TRUE) #set folder directory to compiled
feature_file <- type_files("csv") #set files characteristics
col_name <- c("date_time", "value", "id_sensor", "id_plot") #set column names
data_combine <- combine_files(directory, "csv") %>% 
  dplyr::rename_with(~col_name, everything()) %>% 
  dplyr::arrange(date_time)
save_directory <-system.file("data_ext","data_compile",package="moveworkflow", mustWork=TRUE)
name_file <- paste(basename(directory),"_combine.csv",sep="")
save_file(save_directory,data_combine,"date_time",name_file)#save with name = name_file
rm(list = ls())
```

``` {r eval= FALSE}
## combine noizay rain
feature_file <- type_files("txt") #set file characteristics
directory <- system.file("data_ext","data_raw","pluviometrie","noizay",package="moveworkflow", mustWork=TRUE) #set folder directory to combine
col_name <- c("date_time","row_name","sum","v_rain_mm") # set columns names
data_combine <- combine_files(directory, "txt") %>%
    dplyr::distinct(!!sym(feature_file$name_datetime), pick(1:4)) %>% 
    dplyr::rename_with(~col_name, everything()) %>% 
    dplyr::select(-row_name,-sum) %>% 
    mutate(v_rain_mm = as.numeric(v_rain_mm)) %>% 
    subset(date_time < "2025-04-11 00:00:00") %>% 
    subset(!is.na(v_rain_mm)) %>% 
    dplyr::arrange(date_time)
name_file <- paste(basename(directory),"_rain","_combine.csv",sep="")
save_directory <-system.file("data_ext","data_compile","pluviometrie",package="moveworkflow", mustWork=TRUE)
save_file(save_directory,data_combine,"date_time",name_file) #save with name = name_file

## Select amboise station in meteofrance dataframe
directory <- system.file("data_ext","data_raw","pluviometrie","amboise","amboise_rain.csv",package="moveworkflow", mustWork=TRUE) #set file path
data_rain <- read_file(directory) %>% 
  subset(NOM_USUEL == "AMBOISE")%>% #select amboise station
  dplyr::select(AAAAMMJJHHMN, RR)%>%
  dplyr::mutate(date_time = lubridate::ymd_hm(AAAAMMJJHHMN)+lubridate::hours(1), v_rain_mm=RR)%>% #add 1hours to transforme UTC_date_time in UTC+1_date_time
  dplyr::select(-AAAAMMJJHHMN, -RR) %>%
  subset(date_time >= "2024-04-11 00:00:00") %>% #select project period
  subset(date_time < "2025-04-11 00:00:00") %>% 
  tidyr::drop_na(v_rain_mm) %>% 
  dplyr::arrange(date_time)
name_file <- paste("amboise","_rain","_combine.csv",sep="")
save_directory <-system.file("data_ext","data_compile","pluviometrie",package="moveworkflow", mustWork=TRUE)
save_file(save_directory,data_rain,"date_time",name_file) #save with name = name_file

## Combine the two data_rain
directory <-system.file("data_ext","data_compile","pluviometrie",package="moveworkflow", mustWork=TRUE) #set folder directory
feature_file <- type_files("csv") #set files characteristics
data_combine <- combine_files(directory, "csv") %>% 
  dplyr::mutate(id_file = stringr::str_remove(id_file, "_rain")) %>% 
  dplyr::rename("id_site"=id_file) #add an id_site column
name_file <- paste("rain","_combine.csv",sep="")
save_directory <-system.file("data_ext","data_compile",package="moveworkflow", mustWork=TRUE)
save_file(save_directory,data_combine,"date_time",name_file) #save file with name = name_file
rm(list = ls())
```

``` {r eval= FALSE}
## Correction of diver data by atmospherics pressure
name_plot <- c("A_1","A_2","A_3","N_A","N_F") #chose divers data to correct
for (i in name_plot){
  data_diver <- diver_correct(i)
  save_directory <- system.file("data_ext","data_correct","diver",package="moveworkflow", mustWork=TRUE)
  name_file <- paste(i,"diver_correct.csv",sep="_")
  save_file(save_directory,data_diver,"date_time",name_file) #save file with name = name_file
}

#Compiled data diver corrected
directory <- system.file("data_ext","data_correct","diver",package="moveworkflow",mustWork=TRUE) #set folder path
feature_file <- type_files("csv")
data_combine <- combine_files(directory, "csv") %>% 
  dplyr::select(-id_file) #remove because it's a duplicate information
save_directory <- system.file("data_ext","data_correct",package="moveworkflow",mustWork=TRUE)
name_file <- paste(basename(directory),"_correct.csv",sep="")
save_file(save_directory,data_combine,"date_time",name_file) #save with name = name_file
rm(list = ls())
```

``` {r eval= FALSE}
## Cut tipping
name_plot <- c("A_1","A_2","A_3","N_A","N_F") #select name's plot to cut
directory <- system.file("data_ext","data_compile","tipping_combine.csv",package="moveworkflow", mustWork=TRUE) #set file path
MIT <- lubridate::minutes(15) #set a Minimum Inter-event Time, choose it, after looking at fulls run_off events
feature_ruisselometre <- read_file(system.file("data_ext","data_raw","other_data","features_ruisselometre.csv",package="moveworkflow", mustWork=TRUE)) #charge ruisselometres features
feature_sensor <- read_file(system.file("data_ext","data_raw","other_data","features_sensor.csv",package="moveworkflow", mustWork=TRUE)) #charge sensors features
for (i in name_plot){
data_frame <- read_file(directory) %>%
  subset(id_plot == i) %>%  #charge tipping data
  mutate(date_time = lubridate::ymd_hms(date_time)) %>% 
  arrange(date_time)
list_cut <- cut_data(data_frame, MIT)
data_cut <- list_cut[[1]] %>% 
  dplyr::rowwise() %>%
  mutate(value = sum(!is.na(dplyr::c_across(c(-date_begin,-date_end,-id_event,-value))))) %>% #calculate number of tips per event
  dplyr::ungroup() %>% 
  mutate(v_tip_l = (value * select_feature(feature_sensor,"id_sensor","value",select_feature(feature_ruisselometre,"id_plot","id_tipping",i)))/1000)%>%  #transform number of tips in liter, with sensor features
  mutate(inc_abs_v = value * select_feature(feature_sensor,"id_sensor","inc_abs_sensor",select_feature(feature_ruisselometre,"id_plot","id_tipping",i))/1000) %>% 
  select(date_begin,date_end,id_event,v_tip_l,inc_abs_v)
data_frame <- list_cut[[2]]
#save data event
save_directory <- system.file("data_ext","data_correct","tipping",package="moveworkflow", mustWork=TRUE)
  name_file <- paste(i,"tipping_correct.csv",sep="_")
  save_file(save_directory,data_frame,"date_time",name_file) #save with name = name_file
#save data tipping
save_directory <- system.file("data_ext","data_correct","tipping_ev",package="moveworkflow", mustWork=TRUE)
  name_file <- paste(i,"tipping_ev.csv",sep="_")
  save_file(save_directory,data_cut,c("date_begin","date_end"),name_file) #save with name = name_file
}

##Compile tipping
#tipping_correct
directory <- system.file("data_ext","data_correct","tipping",package="moveworkflow", mustWork=TRUE) #set directory
feature_file <- type_files("csv") #set features file
data_combine <- combine_files(directory,"csv") %>% 
  select(-id_file) #remove because there is already this information
save_directory <- system.file("data_ext","data_correct",package="moveworkflow", mustWork=TRUE)
name_file <- paste("tipping","correct.csv",sep="_")
save_file(save_directory,data_combine,"date_time",name_file)

#tipping_event
directory <- system.file("data_ext","data_correct","tipping_ev",package="moveworkflow", mustWork=TRUE) #set directory
feature_file <- type_files("csv") #set features file
feature_file[["name_datetime"]] <- "date_begin" #set a column name for date
data_combine <- combine_files(directory,"csv") %>% 
  mutate(date_end = ymd_hms(date_end)) %>% 
  subset(v_tip_l>30) %>% #remove data with total volume > 30 l
  rename(id_plot=id_file)
save_directory <- system.file("data_ext","data_correct",package="moveworkflow", mustWork=TRUE)
name_file <- paste("tipping_ev",".csv",sep="")
save_file(save_directory,data_combine,c("date_begin","date_end"),name_file)
rm(list =ls())
```

``` {r eval= FALSE}
## Cut pluviometrie
name_plot <- c("amboise","noizay") #select data_rain to cut
directory <- system.file("data_ext","data_compile","rain_combine.csv",package="moveworkflow", mustWork=TRUE) #set file path
MIT <- lubridate::hours(5) #set MIT = Minimum Inter-event Time, same as tipping
for (i in name_plot){
  if(i == "amboise"){
    TB2V <- lubridate::minutes(6) #set a Time Between 2 Value = time increment if amboise or noizay
  }else{
    TB2V <- lubridate::minutes(5)
  }
data_frame <- read_file(directory) %>% #charge data frame to cut
  subset(id_site == i) %>% 
  mutate(date_time = lubridate::ymd_hms(date_time)) %>% 
  arrange(date_time)
list_cut <- cut_data(data_frame, MIT)
data_cut <- list_cut[[1]] %>%
  mutate(date_end = date_end-MIT+TB2V) %>% #write the good date_end
  dplyr::rowwise() %>%
  mutate(value = sum(dplyr::c_across(c(-date_begin,-date_end,-id_event,-value)), na.rm=TRUE)) %>% #calculate rain volume
  dplyr::ungroup() %>% 
  rename(h_rain_mm = value) %>% 
  select(date_begin,date_end,id_event,h_rain_mm)
data_frame <- list_cut[[2]]
#save data_cut
save_directory <- system.file("data_ext","data_correct","pluviometrie_ev",package="moveworkflow", mustWork=TRUE)
  name_file <- paste(i,"rain","ev.csv",sep="_")
  save_file(save_directory,data_cut,c("date_begin","date_end"),name_file) #save with name = name_file
#save data_frame
  save_directory <- system.file("data_ext","data_correct","pluviometrie",package="moveworkflow", mustWork=TRUE)
  name_file <- paste(i,"rain","correct.csv",sep="_")
  save_file(save_directory,data_frame,"date_time",name_file) #save with name = name_file
}

##Compile rain
#data frame
directory <- system.file("data_ext","data_correct","pluviometrie",package="moveworkflow", mustWork=TRUE) #set folder path
feature_file <- type_files("csv") #set features file
data_combine <- combine_files(directory,"csv") %>% 
  select(-id_file) #remove because it's a duplicate information
save_directory <- system.file("data_ext","data_correct",package="moveworkflow", mustWork=TRUE)
name_file <- paste("rain","correct.csv",sep="_")
save_file(save_directory,data_combine,"date_time",name_file) #save with name = name_file

#data event
directory <- system.file("data_ext","data_correct","pluviometrie_ev",package="moveworkflow", mustWork=TRUE) #set folder path
feature_file <- type_files("csv") #set features file
feature_file[["name_datetime"]] <- "date_begin" #add a date_time column to convert in POSIX.CT
data_combine <- combine_files(directory,"csv") %>% 
  mutate(date_end = ymd_hms(date_end)) %>% 
  dplyr::mutate(id_file = stringr::str_remove(id_file, "_rain")) %>% 
  rename(id_site=id_file)
save_directory <- system.file("data_ext","data_correct",package="moveworkflow", mustWork=TRUE)
name_file <- paste("rain","ev.csv",sep="_")
save_file(save_directory,data_combine,c("date_begin","date_end"),name_file)
rm(list = ls())
```

``` {r eval= FALSE}
## Display diver level to select runoff event
name_plot <- c("A_1","A_2","A_3","N_A","N_F") #select name plot to display
for (i in name_plot){ #print a plot of level variation in time
  dev.new()
  plot_to_select(i)
} 

## Display tipping event to select runoff event
for (i in name_plot){ #print a data frame, with tip runoff event
  directory <- system.file("data_ext","data_correct","tipping_ev.csv",package="moveworkflow", mustWork=TRUE)
  name = paste(i,"_tipping",sep="")
 assign(name, 
        read_file(directory) %>% 
              subset(id_plot == i))
 
  tibble::view(get(name))
}
  #display tipping
  for (i in name_plot){ #print a plot with tips in time
directory <- system.file("data_ext","data_correct","tipping_correct.csv",package="moveworkflow", mustWork=TRUE)
data_tipping <- read_file(directory)%>% 
  subset(id_plot == i) %>% 
  mutate(date_time = ymd_hms(date_time))
k <- plot_ly() %>% #add volume diver
  add_lines(data = data_tipping, x = ~date_time, y = ~value, name = ~id_event, yaxis = 'y1',
            split = ~id_event, color = ~id_event
  )
print(k)
}
```

``` {r eval= FALSE}
##Calculate tipping event metrics
directory <- system.file("data_ext","data_correct","tipping_ev.csv",package="moveworkflow", mustWork=TRUE) #set directory
data_tipping <- read_file(directory) #charge tipping file
data_tipping <- add_column(data_tipping,"duration_h") %>% 
  mutate(date_begin = ymd_hms(date_begin), date_end = ymd_hms(date_end)) %>% 
  mutate(duration_h = as.numeric(difftime(date_end, date_begin, units="hours"))) #calculate duration_h
save_directory <- system.file("data_ext","data_output",package="moveworkflow", mustWork=TRUE)
  name_file <- paste("tipping","ev.csv",sep="_")
  save_file(save_directory,data_tipping,c("date_begin","date_end"),name_file) #save file with name = name_file
rm(list = ls())
```

``` {r eval= FALSE}
##Calculate rain event metrics
directory <- system.file("data_ext","data_correct","rain_ev.csv",package="moveworkflow", mustWork=TRUE) #set directory
data_rain <- read_file(directory) #charge rain's data event
name_col <- c("duration_h", "Imax_mm_h", "Imean_mm_h") 
data_rain <- add_column(data_rain,name_col) %>% #add news column
  mutate(date_begin = ymd_hms(date_begin), date_end = ymd_hms(date_end)) %>% 
  mutate(duration_h = as.numeric(difftime(date_end, date_begin, units="hours"))) #calculate duration
for(i in 1:length(rownames(data_rain))){
  print(paste("select row",i)) 
  directory <- system.file("data_ext","data_correct","rain_correct.csv",package="moveworkflow", mustWork=TRUE)
  data_rain_correct <- read_file(directory) %>%  #charge rain's data
    dplyr::filter(id_site == data_rain$id_site[i]) %>% 
    dplyr::filter(id_event == data_rain$id_event[i]) %>% 
    mutate(date_time = ymd_hms(date_time)) %>% 
    subset(date_time < data_rain$date_end[i])
  if(data_rain$id_site[i] == "amboise"){ # set the good TB2V
    TB2V = 6
  }else{
    TB2V = 5
  }
  #calculate Imax and Imean
  data_rain$Imax_mm_h[i] <- (max(data_rain_correct$v_rain_mm)/TB2V)*60
  data_rain$Imean_mm_h[i] <- (mean(data_rain_correct$v_rain_mm)/TB2V)*60
  print("calcul I_mm_h done")
}
save_directory <- system.file("data_ext","data_output",package="moveworkflow", mustWork=TRUE)
  name_file <- paste("rain","ev.csv",sep="_")
  save_file(save_directory,data_rain,c("date_begin","date_end"),name_file) #save file with name = name_file
  rm(list = ls())
```

```{r eval= FALSE}
##modification of runoff events 
directory <- system.file("data_ext","data_raw","other_data","runoff_event.csv", package="moveworkflow", mustWork=TRUE) #set directory
data_runoff <- read_file(directory) #charge runoff file
directory <- system.file("data_ext","data_raw","other_data","features_ruisselometre.csv", package="moveworkflow", mustWork=TRUE) #set directory
data_ruisselometre <- read_file(directory) #charge ruisselometre
##left joint with tipping
directory <- system.file("data_ext","data_output","tipping_ev.csv", package="moveworkflow", mustWork=TRUE) #set directory
data_tipping <- read_file(directory) #charge tipping file
data_runoff <- data_runoff %>% 
  left_join(data_tipping %>% 
              rename(date_begin_tip = date_begin) %>% 
              rename(date_end_tip = date_end) %>% 
              rename(duration_tip_h = duration_h), by = c("id_tip_event"="id_event","id_plot")) %>% 
  mutate(begin_diver = lubridate::ymd_hm(begin_diver)) %>% 
  mutate(end_diver = lubridate::ymd_hm(end_diver)) %>% 
  mutate(date_begin_tip = lubridate::ymd_hms(date_begin_tip)) %>% 
  mutate(date_end_tip= lubridate::ymd_hms(date_end_tip))
## add columns begin_r and end_r + id_rain_event
data_runoff <- add_column(data_runoff, c("begin_r","end_r", "id_rain_event"))
## match runoff events with rain events
directory <- system.file("data_ext","data_output","rain_ev.csv", package="moveworkflow", mustWork=TRUE) #set directory
data_rain_ev <- read_file(directory) #charge rain_ev file
for(i in 1:length(data_runoff$id_plot)){
  data_runoff$begin_r[i] <- as.character(min(data_runoff$begin_diver[i], data_runoff$date_begin[i], na.rm=TRUE))
data_runoff$end_r[i] <- as.character(max(data_runoff$end_diver[i],data_runoff$date_end[i], na.rm=TRUE))
  data_rain_ev_sub <- data_rain_ev %>% 
    subset(id_site == data_runoff$id_site[i])
  begin_r <- ymd_hms(data_runoff$begin_r[i])
  date_to_match <- as.character(match_date(begin_r, data_rain_ev_sub$date_begin))
  data_runoff$id_rain_event[i] <- select_feature(data_rain_ev_sub,"date_begin","id_event",date_to_match)
}
data_runoff <- add_column(data_runoff, c("v_tank_l","v_runoff_l","inc_abs_v_runoff","inc_rel_v_runoff"))
## calculate volume in tank and run_off
directory <- system.file("data_ext","data_correct","diver_correct.csv", package="moveworkflow", mustWork=TRUE) #set directory
data_diver <- read_file(directory) #charge diver_total
directory <- system.file("data_ext","data_correct","rain_correct.csv", package="moveworkflow", mustWork=TRUE) #set directory
data_rain <- read_file(directory) #charge rain_total
for (i in 1:length(rownames(data_runoff))){
  data_diver_sub <- data_diver%>% 
    mutate(date_time = ymd_hms(date_time)) %>% 
    subset(id_plot == data_runoff$id_plot[i])
  if (data_runoff$type_r[i] != "end_run_off" & data_runoff$sonde_diver[i] == "yes"){
    #fixe level begin and level end
    level_begin <- (data_diver_sub %>% 
                      dplyr::filter(date_time >= ymd_hms(data_runoff$begin_diver[i]) - lubridate::hours(1), date_time <= ymd_hms(data_runoff$begin_diver[i])) %>% 
                      dplyr::summarise(mean_begin = mean(level_cm, na.rm=TRUE)))[1,1]
    inc_level_begin <- (data_diver_sub %>% 
                      dplyr::filter(date_time >= ymd_hms(data_runoff$begin_diver[i]) - lubridate::hours(1), date_time <= ymd_hms(data_runoff$begin_diver[i])) %>% 
                      dplyr::summarise(sd_begin = sd(level_cm, na.rm=TRUE)))[1,1]+1.5
    level_end <- (data_diver_sub %>% 
                      dplyr::filter (date_time >= ymd_hms(data_runoff$end_diver[i]) , date_time <= ymd_hms(data_runoff$end_diver[i]) + lubridate::hours(1)) %>% 
                      dplyr::summarise(mean_end = mean(level_cm, na.rm=TRUE)))[1,1]
    inc_level_end <- (data_diver_sub %>% 
                      dplyr::filter(date_time >= ymd_hms(data_runoff$end_diver[i]) , date_time <= ymd_hms(data_runoff$end_diver[i])+ lubridate::hours(1)) %>% 
                      dplyr::summarise(sd_end = sd(level_cm, na.rm=TRUE)))[1,1]+1.5
    #calculate runoff_volume
    v_tank_l <- (level_end - level_begin)*11.2
  }else if (data_runoff$type_r[i] == "end_run_off"){
    level_begin <- (data_diver_sub$level_cm[data_diver_sub$date_time == ymd_hms(data_runoff$begin_diver[i])])
    inc_level_begin <- 1.5
    level_end <- (data_diver_sub %>% 
                      dplyr::filter (date_time >= ymd_hms(data_runoff$end_diver[i]) , date_time <= ymd_hms(data_runoff$end_diver[i]) + lubridate::hours(1)) %>% 
                      dplyr::summarise(mean_end = mean(level_cm, na.rm=TRUE)))[1,1]
    inc_level_end <- (data_diver_sub %>% 
                      dplyr::filter(date_time >= ymd_hms(data_runoff$end_diver[i]) , date_time <= ymd_hms(data_runoff$end_diver[i])+ lubridate::hours(1)) %>% 
                      dplyr::summarise(sd_end = sd(level_cm, na.rm=TRUE)))[1,1]+1.5
    v_tank_l <- (level_end - level_begin)*11.2
  }else{
    v_tank_l <- NA
  }
    data_runoff$v_tank_l[i] <- v_tank_l
    data_rain_sub <- data_rain %>% 
     subset(id_site == data_runoff$id_site[i])
    data_runoff$v_gutter_l[i] <- ((data_rain_sub %>% 
      mutate(date_time = lubridate::ymd_hms(date_time)) %>% 
      subset(id_event == data_runoff$id_rain_event[i]) %>% 
      dplyr::filter(date_time >= data_runoff$begin_r[i]) %>% 
      dplyr::summarise(volume_rain = sum(v_rain_mm)))[1,1])*
      select_feature(data_ruisselometre, "id_plot", "area_gutter_m2", data_runoff$id_plot[i])
    data_runoff$v_runoff_l[i] <- sum(data_runoff$v_tank_l[i], data_runoff$v_tip_l[i], na.rm =TRUE) - data_runoff$v_gutter_l[i]
    data_runoff$inc_abs_v_runoff[i] <- sum(data_runoff$inc_abs_v[i],(inc_level_end+inc_level_begin)*11.2,na.rm=TRUE)
    data_runoff$inc_rel_v_runoff[i] <- (data_runoff$inc_abs_v_runoff[i]/data_runoff$v_runoff_l[i])*100
}
    data_runoff <- data_runoff %>% 
  select(id_site, id_plot, id_runoff_ev, precision_r, id_sampling, id_eavy_load, id_rain_event, begin_r, end_r, v_runoff_l, inc_abs_v_runoff, inc_rel_v_runoff) %>% 
  mutate(begin_r = lubridate::ymd_hms(begin_r)) %>% 
  mutate(end_r = lubridate::ymd_hms(end_r))
## save file
save_directory <- system.file("data_ext","data_compile",package="moveworkflow",mustWork=TRUE)
name_file <- paste("runoff.csv",sep="")
save_file(save_directory,data_runoff,c("begin_r","end_r"),name_file) #save with name = name_file
rm(list = ls())
```

```{r eval= FALSE}
##correct event need to be correct
directory <- system.file("data_ext","data_compile","runoff.csv", package="moveworkflow", mustWork=TRUE) #set directory
data_runoff <- read_file(directory)  #charge runoff file
data_runoff <- correct_runoff(data_runoff, "A_1","event_230")
data_runoff <- correct_runoff(data_runoff, "A_3","event_230")
data_runoff <- correct_runoff(data_runoff, "A_3","event_276")
data_runoff <- correct_runoff(data_runoff, "A_3","event_293")
data_runoff <- correct_runoff(data_runoff, "N_A","event_145")
data_runoff <- correct_runoff(data_runoff, "N_F","event_89")
data_runoff$precision_r[data_runoff$id_plot == "N_F" & data_runoff$id_rain_event == "event_89"] <- "medium"
#when diver is hs, we can add 1m3 to runoff and put runoff in good
# R17 in A_3
data_runoff$v_runoff_l[data_runoff$id_plot == "A_3" & data_runoff$id_runoff_ev == "17"] <- data_runoff$v_runoff_l[data_runoff$id_plot == "A_3" & data_runoff$id_runoff_ev == "17"] + 840
data_runoff$precision_r[data_runoff$id_plot == "A_3" & data_runoff$id_runoff_ev == "17"] <- "good"
# R18 in N_F
data_runoff$v_runoff_l[data_runoff$id_plot == "N_F" & data_runoff$id_runoff_ev == "18"] <- data_runoff$v_runoff_l[data_runoff$id_plot == "N_F" & data_runoff$id_runoff_ev == "18"] + 840
data_runoff$precision_r[data_runoff$id_plot == "N_F" & data_runoff$id_runoff_ev == "18"] <- "good"
# R22 in N_F
data_runoff$v_runoff_l[data_runoff$id_plot == "N_F" & data_runoff$id_runoff_ev == "22"] <- data_runoff$v_runoff_l[data_runoff$id_plot == "N_F" & data_runoff$id_runoff_ev == "22"] + 840
data_runoff$precision_r[data_runoff$id_plot == "N_F" & data_runoff$id_runoff_ev == "22"] <- "good"
#calculate CR
directory <- system.file("data_ext","data_raw","other_data","features_ruisselometre.csv", package="moveworkflow", mustWork=TRUE)
data_ruisselometre <- read_file(directory)
directory <- system.file("data_ext","data_output","rain_ev.csv", package="moveworkflow", mustWork=TRUE)
data_rain_ev <- read_file(directory)
## calculate runoff_mm
data_runoff <- add_column(data_runoff, c("h_runoff_mm"))
for(i in 1:length(rownames(data_runoff))){
data_runoff$h_runoff_mm[i] <- data_runoff$v_runoff_l[i] / 
      select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i])
}
## left_join with rain event
data_runoff <- data_runoff %>% 
  left_join(data_rain_ev %>% 
              rename(date_begin_rain = date_begin) %>% 
              rename(date_end_rain = date_end) %>% 
              rename(duration_rain_h = duration_h), by = c("id_rain_event" = "id_event","id_site"))
## calculate CR
data_runoff <- add_column(data_runoff, c("CR", "inc_abs_CR", "inc_rel_CR"))
data_runoff<- data_runoff %>% 
  mutate(CR = (h_runoff_mm/h_rain_mm)*100) %>%  
  mutate(inc_abs_CR = ((inc_rel_v_runoff/100) + 0.05)*CR) %>% 
  mutate(inc_rel_CR = (inc_abs_CR/CR)*100)
data_runoff <- add_column(data_runoff, c("duration_runoff_h","imbibition_h","drainage_h"))
data_runoff <- data_runoff %>% 
  mutate(begin_r = ymd_hms(begin_r)) %>% 
  mutate(end_r = ymd_hms(end_r)) %>% 
  mutate(date_begin_rain = ymd_hms(date_begin_rain)) %>% 
  mutate(date_end_rain = ymd_hms(date_end_rain)) %>% 
  mutate(duration_runoff_h = as.numeric(difftime(end_r, begin_r, units='hours'))) %>% 
  mutate(imbibition_h = as.numeric(difftime(begin_r, date_begin_rain, units='hours'))) %>% 
  mutate(drainage_h = as.numeric(difftime(end_r, date_end_rain, units='hours'))) %>% 
  arrange(begin_r) %>% 
  arrange(id_plot)
## second correction, add rain to event. The CR will be litteler
data_runoff <- second_correct(data_runoff)
## save file
save_directory <- system.file("data_ext","data_correct",package="moveworkflow",mustWork=TRUE)
name_file <- paste("runoff_measured.csv",sep="")
save_file(save_directory,data_runoff,c("begin_r","end_r","date_begin_rain","date_end_rain"),name_file) #save with name = name_file
rm(list = ls())
```

```{r eval= FALSE}
##plot to zoom on events
name_plot = c("A_1","A_2","A_3","N_A","N_F")
for (i in name_plot){
plot <- plot_to_see(i, lubridate::ymd("2024_04_11"), lubridate::ymd("2025_04_11"))
print(plot)
}
rm(list=ls())
```

```{r eval= FALSE}
## put yes / no / maybe, to compare rain events
plot_name <- c("N_F","A_1","A_2","A_3","N_A")
for(i in plot_name){
  data <- type_rain(i)
}


```

```{r eval= FALSE}
##add other value 
directory <- system.file("data_ext","data_output","runoff_imputed.csv", package="moveworkflow", mustWork=TRUE) #set directory
data_runoff <- read_file(directory) %>%   #charge runoff file
  subset(note != "runoff_low")
directory <- system.file("data_ext","data_raw","other_data","features_ruisselometre.csv", package="moveworkflow", mustWork=TRUE)
data_ruisselometre <- read_file(directory)
## add good h_run_off_min
for (i in 1:length(rownames(data_runoff))){
  data_runoff$min_h_runoff_mm[i] <- max(data_runoff$min_h_runoff_mm[i],data_runoff$old_min_runoff[i], na.rm=TRUE)
}
data_runoff <- data_runoff %>% 
  select(-old_min_runoff)
## calculate volume in liter
for(i in 1:length(rownames(data_runoff))){
data_runoff$v_min_runoff_l[i] <- data_runoff$min_h_runoff_mm[i]* 
      select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i])
data_runoff$v_max_runoff_l[i] <- data_runoff$max_h_runoff_mm[i]* 
      select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i])
}
## left join with data labo
directory <- system.file("data_ext","data_raw","other_data","data_measures_labo.csv", package="moveworkflow", mustWork=TRUE) #set directory
data_labo <- read_file(directory) #charge measures labo file
data_runoff <- data_runoff %>% 
  left_join(
    data_labo %>% 
      select(id_sampling, id_plot, c_MES_g_l, mass_eavy_load_g, c_cu_total_ppb, c_cu_dissolved_ppb, inc_abs_MES, inc_rel_MES, inc_abs_cu_total, inc_rel_cu_total, inc_abs_cu_dissolved, inc_rel_cu_dissolved),
  by = c("id_plot", "id_sampling"))
##calculate MES and CU
for(i in 1:length(rownames(data_runoff))){
  data_runoff$mass_min_MES_kg_ha[i] <- (((data_runoff$v_min_runoff_l[i]*data_runoff$c_MES_g_l[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000 - ((((data_runoff$v_min_runoff_l[i]*data_runoff$c_MES_g_l[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000)*(data_runoff$inc_rel_MES[i]/100)
  data_runoff$mass_max_MES_kg_ha[i] <- (((data_runoff$v_max_runoff_l[i]*data_runoff$c_MES_g_l[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000 + ((((data_runoff$v_max_runoff_l[i]*data_runoff$c_MES_g_l[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000)*(data_runoff$inc_rel_MES[i]/100)
  data_runoff$mass_min_cu_total_g_ha[i] <- ((((data_runoff$v_min_runoff_l[i]*data_runoff$c_cu_total_ppb[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000)/1000 - (((((data_runoff$v_min_runoff_l[i]*data_runoff$c_cu_total_ppb[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000)/1000)*(data_runoff$inc_rel_cu_total[i]/100)
  data_runoff$mass_max_cu_total_g_ha[i] <- ((((data_runoff$v_max_runoff_l[i]*data_runoff$c_cu_total_ppb[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000)/1000 + (((((data_runoff$v_max_runoff_l[i]*data_runoff$c_cu_total_ppb[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000)/1000)*(data_runoff$inc_rel_cu_total[i]/100) 
  data_runoff$mass_min_cu_dissolved_g_ha[i] <- ((((data_runoff$v_min_runoff_l[i]*data_runoff$c_cu_dissolved_ppb[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000)/1000 - (((((data_runoff$v_min_runoff_l[i]*data_runoff$c_cu_dissolved_ppb[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000)/1000)*(data_runoff$inc_rel_cu_dissolved[i]/100) 
  data_runoff$mass_max_cu_dissolved_g_ha[i] <- ((((data_runoff$v_max_runoff_l[i]*data_runoff$c_cu_dissolved_ppb[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000)/1000 + (((((data_runoff$v_max_runoff_l[i]*data_runoff$c_cu_dissolved_ppb[i])/1000)/select_feature(data_ruisselometre, "id_plot", "area_plot_m2", data_runoff$id_plot[i]))*10000)/1000)*(data_runoff$inc_rel_cu_dissolved[i]/100) 
}
## save file
save_directory <- system.file("data_ext","data_output",package="moveworkflow",mustWork=TRUE)
name_file <- paste("runoff.csv",sep="")
save_file(save_directory,data_runoff,c(),name_file) #save with
rm(list=ls())
```

```{r eval= FALSE}
## sumup in days
## charge runoff file
save_directory <- system.file("data_ext","data_output","daily_data",package="moveworkflow",mustWork=TRUE)
name_plot <- c("A_1","A_2","A_3","N_A","N_F") 
for (i in name_plot){
  data_daily <- data_in_days(i)
  name_file <- paste(i,"daily_data.csv",sep="_")
  save_file(save_directory,data_daily,"date_time",name_file) #save with name = name_file
}
##Compiled all daily_data
directory <- system.file("data_ext","data_output","daily_data",package="moveworkflow", mustWork=TRUE) #set folder directory to compiled
feature_file <- type_files("csv") #set file characteristic
data_combine <- combine_files(directory, "csv") %>% 
  dplyr::rename(id_plot = id_file) %>% 
  dplyr::arrange(id_plot)
save_directory <-system.file("data_ext","data_output",package="moveworkflow", mustWork=TRUE)
name_file <- paste(basename(directory),"_combine.csv",sep="")
save_file(save_directory,data_combine,"date_time",name_file) #save with name = name_file
rm(list = ls())
```

